### ISSUE TITLE
@decorate creates method shared by all instances

### ISSUE THREAD

**Issue by panrafal** [jayphelps/core-decorators.js#67] opened 2016-04-12 15:53 UTC
`@decorate` works on the prototype level - which is fast - but the proposed use of `decorate(_.memoize)` makes the memoization *shared* between object instances. As method calls are memoized by first argument, the changing `this` does not make any effect. This code will not work as expected:

``` js
class Foo {
  @decorate(_.memoize)
  foo() {
    return this
  }
}

let a = new Foo()
let b = new Foo()
expect(a.foo() !== b.foo()) // should be different, but it's the same
```

The same goes for any other use of `@decorate`. I think it would be beneficial to create a separate `@decorateInstance` or change how the original one works, as it's not intuitive right now. What do you think?

**Comment by jayphelps** [comment] 2016-04-13 01:05
@panrafal this is definitely unintended behavior. Looking into it. Thank you!

**Comment by jayphelps** [comment] 2016-04-13 01:59
I believe I've solve this with #68.

**Comment by jasonayre** [comment] 2016-04-13 16:51
+1, running into this issue as well

Also I pulled down that branch @jayphelps and added additional specs because I was skeptical as to whether it was solved, but as far as I can tell it seems to have been.

**Comment by jayphelps** [comment] 2016-04-13 16:51
@jasonayre by all means please do provide more tests!! 👯  Thanks for confirming too!

**Comment by jayphelps** [comment] 2016-04-13 17:19
Released as `v0.12.1`. Please confirm this resolved things for both of you.

**Comment by jasonayre** [comment] 2016-04-13 18:08
Updating to 0.12.1 seems to have solved the issue on my end, thanks so much!  
  

On Apr 13 2016, at 11:19 am, Jay Phelps &lt;notifications@github.com&gt;
wrote:  

> Reopened [#67](https://github.com/jayphelps/core-decorators.js/issues/67).

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on
GitHub](https://github.com/jayphelps/core-decorators.js/issues/67#event-626124
270)![](https://github.com/notifications/beacon/AAJdzKrcBJkTI94q4LeBWE6tevmRVv
6Vks5p3SWZgaJpZM4IFiWF.gif)

**Comment by jayphelps** [comment] 2016-04-20 08:25
Seems to be resolved.

**Closed by jayphelps** 2016-04-20 08:25 UTC
Labels: bug, confirmed
